/**
 * Controlled India-Wide Spatial & Location Registry
 * Validated geographical coordinates, administrative tiers, and climatological zones.
 */

const INDIA_LOCATIONS_REGISTRY = [
  // 1. National Capital & Northwest Plains
  {
    location_id: 'del-delhi',
    name: 'New Delhi',
    country: 'India',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    latitude: 28.6139,
    longitude: 77.2090,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Subtropical Semi-Arid',
    population: 16787941,
    population_density: 11320,
    is_urban: true,
  },
  {
    location_id: 'raj-jaipur',
    name: 'Jaipur',
    country: 'India',
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    latitude: 26.9124,
    longitude: 75.7873,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Hot Semi-Arid',
    population: 3073350,
    population_density: 6300,
    is_urban: true,
  },
  {
    location_id: 'raj-jodhpur',
    name: 'Jodhpur',
    country: 'India',
    state: 'Rajasthan',
    district: 'Jodhpur',
    city: 'Jodhpur',
    latitude: 26.2389,
    longitude: 73.0243,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Hot Arid (Thar)',
    population: 1033918,
    population_density: 4500,
    is_urban: true,
  },
  {
    location_id: 'raj-bikaner',
    name: 'Bikaner',
    country: 'India',
    state: 'Rajasthan',
    district: 'Bikaner',
    city: 'Bikaner',
    latitude: 28.0229,
    longitude: 73.3119,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Hyper-Arid Severe Heat',
    population: 644406,
    population_density: 3800,
    is_urban: true,
  },
  {
    location_id: 'pun-ludhiana',
    name: 'Ludhiana',
    country: 'India',
    state: 'Punjab',
    district: 'Ludhiana',
    city: 'Ludhiana',
    latitude: 30.9010,
    longitude: 75.8573,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Semi-Arid Plains',
    population: 1618879,
    population_density: 9800,
    is_urban: true,
  },

  // 2. Western India & Gujarat Arid/Coastal Belt
  {
    location_id: 'guj-ahmedabad',
    name: 'Ahmedabad',
    country: 'India',
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    latitude: 23.0225,
    longitude: 72.5714,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Hot Semi-Arid',
    population: 5577940,
    population_density: 12500,
    is_urban: true,
  },
  {
    location_id: 'guj-surat',
    name: 'Surat',
    country: 'India',
    state: 'Gujarat',
    district: 'Surat',
    city: 'Surat',
    latitude: 21.1702,
    longitude: 72.8311,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Tropical Wet & Dry',
    population: 4467797,
    population_density: 13700,
    is_urban: true,
  },
  {
    location_id: 'mah-mumbai',
    name: 'Mumbai',
    country: 'India',
    state: 'Maharashtra',
    district: 'Mumbai Suburban',
    city: 'Mumbai',
    latitude: 19.0760,
    longitude: 72.8777,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Tropical Coastal Compound Heat',
    population: 12442373,
    population_density: 21000,
    is_urban: true,
  },
  {
    location_id: 'mah-nagpur',
    name: 'Nagpur',
    country: 'India',
    state: 'Maharashtra',
    district: 'Nagpur',
    city: 'Nagpur',
    latitude: 21.1458,
    longitude: 79.0882,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Tropical Dry Vidarbha Hotspot',
    population: 2405665,
    population_density: 6500,
    is_urban: true,
  },
  {
    location_id: 'mah-pune',
    name: 'Pune',
    country: 'India',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    latitude: 18.5204,
    longitude: 73.8567,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Hot Semi-Arid Plateau',
    population: 3124458,
    population_density: 9400,
    is_urban: true,
  },

  // 3. Central & Gangetic Plain Heat Belts
  {
    location_id: 'mp-bhopal',
    name: 'Bhopal',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    latitude: 23.2599,
    longitude: 77.4126,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Humid Subtropical',
    population: 1798218,
    population_density: 8500,
    is_urban: true,
  },
  {
    location_id: 'mp-gwalior',
    name: 'Gwalior',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Gwalior',
    city: 'Gwalior',
    latitude: 26.2183,
    longitude: 78.1828,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Extreme Summer Hotspot',
    population: 1069276,
    population_density: 5600,
    is_urban: true,
  },
  {
    location_id: 'up-lucknow',
    name: 'Lucknow',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    latitude: 26.8467,
    longitude: 80.9462,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Humid Subtropical',
    population: 2817105,
    population_density: 7500,
    is_urban: true,
  },
  {
    location_id: 'up-varanasi',
    name: 'Varanasi',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    city: 'Varanasi',
    latitude: 25.3176,
    longitude: 82.9739,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Humid Subtropical Gangetic',
    population: 1198491,
    population_density: 10500,
    is_urban: true,
  },
  {
    location_id: 'up-prayagraj',
    name: 'Prayagraj (Allahabad)',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Prayagraj',
    city: 'Prayagraj',
    latitude: 25.4358,
    longitude: 81.8463,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Gangetic Heatwave Core',
    population: 1168385,
    population_density: 7200,
    is_urban: true,
  },
  {
    location_id: 'bih-patna',
    name: 'Patna',
    country: 'India',
    state: 'Bihar',
    district: 'Patna',
    city: 'Patna',
    latitude: 25.5941,
    longitude: 85.1376,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Humid Gangetic Heat Zone',
    population: 1684222,
    population_density: 12000,
    is_urban: true,
  },
  {
    location_id: 'bih-gaya',
    name: 'Gaya',
    country: 'India',
    state: 'Bihar',
    district: 'Gaya',
    city: 'Gaya',
    latitude: 24.7914,
    longitude: 85.0002,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Extreme Summer Hotspot',
    population: 470839,
    population_density: 5100,
    is_urban: true,
  },

  // 4. Southern & Deccan Plateau Belts
  {
    location_id: 'tel-hyderabad',
    name: 'Hyderabad',
    country: 'India',
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    latitude: 17.3850,
    longitude: 78.4867,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Tropical Wet & Dry / Semi-Arid',
    population: 6809970,
    population_density: 11000,
    is_urban: true,
  },
  {
    location_id: 'ap-vijayawada',
    name: 'Vijayawada',
    country: 'India',
    state: 'Andhra Pradesh',
    district: 'NTR',
    city: 'Vijayawada',
    latitude: 16.5062,
    longitude: 80.6480,
    timezone: 'Asia/Kolkata',
    climate_zone: 'High Humidity Coastal Heat',
    population: 1034358,
    population_density: 8900,
    is_urban: true,
  },
  {
    location_id: 'kar-bengaluru',
    name: 'Bengaluru',
    country: 'India',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    latitude: 12.9716,
    longitude: 77.5946,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Tropical Savanna Plateau',
    population: 8443675,
    population_density: 11500,
    is_urban: true,
  },
  {
    location_id: 'tn-chennai',
    name: 'Chennai',
    country: 'India',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    latitude: 13.0827,
    longitude: 80.2707,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Tropical Wet Coastal Compound Heat',
    population: 7088000,
    population_density: 17000,
    is_urban: true,
  },
  {
    location_id: 'ker-kochi',
    name: 'Kochi',
    country: 'India',
    state: 'Kerala',
    district: 'Ernakulam',
    city: 'Kochi',
    latitude: 9.9312,
    longitude: 76.2673,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Tropical Monsoon Coastal',
    population: 677381,
    population_density: 7100,
    is_urban: true,
  },

  // 5. Eastern & Coastal Hotspots
  {
    location_id: 'wb-kolkata',
    name: 'Kolkata',
    country: 'India',
    state: 'West Bengal',
    district: 'Kolkata',
    city: 'Kolkata',
    latitude: 22.5726,
    longitude: 88.3639,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Tropical Wet & Dry High Heat Index',
    population: 4496694,
    population_density: 24000,
    is_urban: true,
  },
  {
    location_id: 'odi-bhubaneswar',
    name: 'Bhubaneswar',
    country: 'India',
    state: 'Odisha',
    district: 'Khurda',
    city: 'Bhubaneswar',
    latitude: 20.2961,
    longitude: 85.8245,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Tropical Wet Coastal Heat',
    population: 843402,
    population_density: 6100,
    is_urban: true,
  },
  {
    location_id: 'odi-titlagarh',
    name: 'Titlagarh',
    country: 'India',
    state: 'Odisha',
    district: 'Balangir',
    city: 'Titlagarh',
    latitude: 20.3000,
    longitude: 83.1400,
    timezone: 'Asia/Kolkata',
    climate_zone: 'Extreme Summer Hotspot (Furnace City)',
    population: 34500,
    population_density: 2800,
    is_urban: false,
  },
];

/**
 * Returns location record by location_id or coordinate proximity
 */
function getLocationById(locationId) {
  if (!locationId || typeof locationId !== 'string') return null;
  const clean = locationId.trim().toLowerCase();
  return (
    INDIA_LOCATIONS_REGISTRY.find(l => l.location_id === clean || l.name.toLowerCase() === clean) ||
    INDIA_LOCATIONS_REGISTRY.find(l => clean.includes(l.name.toLowerCase())) ||
    null
  );
}

/**
 * Returns all registered India locations
 */
function getAllLocations() {
  return [...INDIA_LOCATIONS_REGISTRY];
}

module.exports = {
  INDIA_LOCATIONS_REGISTRY,
  getLocationById,
  getAllLocations,
};
